output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
member-warnings: false

autodetect: false

ignore-paths:
  - tests

bandit:
  run: true

pyroma:
  run: true

pep8:
  full: true

pep257:
  disable:
    - D105
    - D107
    - D203
    - D212
    - D212
    - D400
  run: true
