pep257:
  # see http://pep257.readthedocs.io/en/latest/error_codes.html
  disable: [
    # For short descriptions it makes sense not to end with a period:
    D400,  # First line should end with a period
    # Disable because not part of PEP257 official convention:
    D203,  # 1 blank line required before class docstring
  ]